### ISSUE TITLE
Login page isn't Redirecting to the home page even after having the required NFT in the wallet

### ISSUE THREAD

**Issue by atharao** [thirdweb-example/nft-gated-website#22]
I have used this repo for NFT gated website but at the login page the wallet gets connected after that it supposes to enter into the new page but we remain there only 
and the code of the login page is different in the youtube video in that video the person is able to connect his wallet and able to enter into a new page 
please update the code if possible

![image](https://github.com/thirdweb-example/nft-gated-website/assets/116030767/ed463b2c-2b0a-4cc0-9bb3-e967d12e47f9)

after this, a new page should get open that's the whole point of this website

**Comment by saminacodes** [comment]
Hi, we just updated the repo today - could you take a look and see if that resolved it

**Comment by atharao** [comment]
Yes, the PR is absolutely correct When I merged the recently changed files of this PR in my project my issue got solved Thank you team Thirdweb( @saminacodes) for your time.
Source of PR: https://github.com/thirdweb-example/nft-gated-website/pull/23
